### PR TITLE
Sort devices by generation

### PR DESCRIPTION
**Pull request by liamdon**
I added the 11 series devices previously, but it is helpful for the enum to sort by generation such that the iPhone 11 appears after the iPhone XS - this corrects my previous placement.

### CODE REVIEW

**Comment by InderKumarRathore** [comment]
This won't solve the problem, we need to update the script file to cater this issue, other wise next time someone runs the script for new device it will override the old one

**Comment by InderKumarRathore** [comment]
BTW this is good idea

**Comment by Kaspik** [comment]
I think the plist file for generator is correct, but this wasn't as it was added manually?

**Comment by InderKumarRathore** [comment]
Yes the plist file is correct, but the logic inside the main.swift script file is such that it was not sorting the enums. Now I have added the logic for that and is available in latest pod.

**Pull request closed without merging**
